service: billingService

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  role: ${file(../roleARN.yaml):roles.LabRole}
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, 'dev'}

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /billing/invoices
          method: any
          cors: true
      - http:
          path: /billing/invoices/{invoice_id}
          method: any
          cors: true

resources:
  Resources:
    BillingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: invoice_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: invoice_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
